repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: local
    hooks:
      - id: typstyle
        name: typstyle
        entry: typstyle
        language: system
        types: [file]
        files: \.typ$
        args: ["-i", "-l", "120"]
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.6.0"
    hooks:
      - id: editorconfig-checker
        alias: ec
