// Input validation shared by the public template function.
#let validate(config) = {
  assert(type(config.page-count) == int, message: "page-count must be an integer")
  assert(config.page-count >= 1, message: "page-count must be at least 1")
  assert(config.margin >= 0pt, message: "margin must not be negative")
  assert(config.horizontal-margin >= 0pt, message: "horizontal-margin must not be negative")
  assert(config.margin * 2 < 210mm, message: "margin leaves no vertical writing area")
  assert(config.horizontal-margin * 2 < 297mm, message: "horizontal-margin leaves no writing area")
  assert(config.grid-size > 0pt, message: "grid-size must be greater than zero")
  assert(config.grid-thickness >= 0pt, message: "grid-thickness must not be negative")
  assert(config.column-width > 0pt, message: "column-width must be greater than zero")
  assert(config.header-height >= 0pt, message: "header-height must not be negative")
  assert(config.header-height < 210mm - 2 * config.margin, message: "header-height exceeds the writing area")
  assert(type(config.title-grid-columns) == int, message: "title-grid-columns must be an integer")
  assert(type(config.title-grid-rows) == int, message: "title-grid-rows must be an integer")
  assert(config.title-grid-columns >= 1, message: "title-grid-columns must be at least 1")
  assert(config.title-grid-rows >= 1, message: "title-grid-rows must be at least 1")
  assert(config.border-thickness >= 0pt, message: "border-thickness must not be negative")
  assert(config.spacer-thickness >= 0pt, message: "spacer-thickness must not be negative")
  assert(config.page-number-width > 0pt, message: "page-number-width must be greater than zero")
  assert(config.page-number-height > 0pt, message: "page-number-height must be greater than zero")
  assert(config.watermark-width > 0%, message: "watermark-width must be greater than zero")
  assert(config.watermark-width <= 100%, message: "watermark-width must not exceed 100%")
  assert(config.watermark-opacity >= 0%, message: "watermark-opacity must not be negative")
  assert(config.watermark-opacity <= 100%, message: "watermark-opacity must not exceed 100%")
  assert(type(config.show-page-numbers) == bool, message: "show-page-numbers must be boolean")
  assert(type(config.show-watermark) == bool, message: "show-watermark must be boolean")
  assert(type(config.show-credits) == bool, message: "show-credits must be boolean")
  config
}
